language: python
python:
  - "3.8"
os:
  - linux
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-mpl
  - pip install .
script:
  - pytest --cov-report=xml --cov=isopy tests/
  - pytest --mpl --mpl-baseline-path=tests/baseline_images tests/test_plotting.py
after_sucess:
  - codecov
deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  distrobutions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master