language: python
python:
  - "3.9"
os:
  - linux
  - osx
  - windows
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
  - pip install .
script:
  - pytest --cov-report=xml --cov=isopy tests/
after_sucess:
  - codecov
deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  distrobutions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master