coverage:
  status:
    project:
      default: false
      core:
        target: 90%
        paths: ["!isopy/toolbox/"]
      toolbox:
        paths: ["isopy/toolbox/"]
        target: 75%
    patch: off

